/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_api_v1_admin_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Collection */
        post: operations["create_collection_api_v1_admin_collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Collection */
        patch: operations["update_collection_api_v1_admin_collections__collection_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Location */
        post: operations["create_location_api_v1_admin_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Location */
        delete: operations["delete_location_api_v1_admin_locations__location_id__delete"];
        options?: never;
        head?: never;
        /** Update Location */
        patch: operations["update_location_api_v1_admin_locations__location_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Admin */
        get: operations["read_admin_api_v1_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media-assets/{asset_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Asset Processing */
        post: operations["retry_asset_processing_api_v1_admin_media_assets__asset_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/memberships/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Membership */
        put: operations["update_membership_api_v1_admin_memberships__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_admin_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_v1_admin_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Update Session */
        patch: operations["update_session_api_v1_admin_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/sessions/{session_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session Asset */
        post: operations["create_session_asset_api_v1_admin_sessions__session_id__assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sessions/{session_id}/processing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Session Processing */
        get: operations["read_session_processing_api_v1_admin_sessions__session_id__processing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User Role */
        patch: operations["update_user_role_api_v1_admin_users__user_id__role_patch"];
        trace?: never;
    };
    "/api/v1/atlas/dawn/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Dawn */
        get: operations["get_current_dawn_api_v1_atlas_dawn_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/atlas/dawn/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Follow Dawn */
        get: operations["get_follow_dawn_api_v1_atlas_dawn_follow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/atlas/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Atlas Points */
        get: operations["get_atlas_points_api_v1_atlas_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Collections */
        get: operations["list_collections_api_v1_collections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collection */
        get: operations["get_collection_api_v1_collections__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_v1_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{locator}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Location */
        get: operations["get_location_api_v1_locations__locator__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memberships/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read My Membership */
        get: operations["read_my_membership_api_v1_memberships_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Featured Sessions */
        get: operations["list_featured_sessions_api_v1_sessions_featured_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{locator}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_sessions__locator__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Annotations */
        get: operations["get_annotations_api_v1_sessions__session_id__annotations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/bird-parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bird Parts */
        get: operations["get_bird_parts_api_v1_sessions__session_id__bird_parts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/playback-grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Playback Grant */
        post: operations["create_playback_grant_api_v1_sessions__session_id__playback_grants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Waveform */
        get: operations["get_waveform_api_v1_sessions__session_id__waveform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminMediaAssetRead */
        AdminMediaAssetRead: {
            /** Checksum */
            checksum: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Seconds */
            duration_seconds: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["MediaKind"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Mime Type */
            mime_type: string;
            /** Processing Jobs */
            processing_jobs?: components["schemas"]["ProcessingJobRead"][];
            /** @default uploaded */
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Size Bytes */
            size_bytes: number | null;
            /** Storage Key */
            storage_key: string;
        };
        /** AtlasCluster */
        AtlasCluster: {
            /** Count */
            count: number;
            /** Habitats */
            habitats?: string[];
            /** Id */
            id: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Type
             * @default cluster
             * @constant
             */
            type: "cluster";
        };
        /** AtlasPoint */
        AtlasPoint: {
            /** Coordinate Visibility */
            coordinate_visibility: string;
            /** Country Code */
            country_code?: string | null;
            /** Description */
            description?: string | null;
            /** Habitat */
            habitat?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            latest_session?: components["schemas"]["AtlasSessionSummary"] | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Region */
            region?: string | null;
            /** Sensitivity Level */
            sensitivity_level: string;
            /** Session Count */
            session_count: number;
            /** Slug */
            slug: string;
            /** Timezone */
            timezone: string;
            /**
             * Type
             * @default point
             * @constant
             */
            type: "point";
        };
        /** AtlasPointsResponse */
        AtlasPointsResponse: {
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            /** Cache Key */
            cache_key: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "points" | "clusters";
            /** Points */
            points: (components["schemas"]["AtlasPoint"] | components["schemas"]["AtlasCluster"])[];
            /** Zoom */
            zoom: number;
        };
        /** AtlasSessionSummary */
        AtlasSessionSummary: {
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** AuditEventRead */
        AuditEventRead: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event Type */
            event_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ip Address */
            ip_address: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Subject Id */
            subject_id: string | null;
            /** Subject Type */
            subject_type: string;
            /** User Agent */
            user_agent: string | null;
        };
        /** BirdPartsResponse */
        BirdPartsResponse: {
            /** Analysis Model Version */
            analysis_model_version?: string | null;
            /** Analysis Provider */
            analysis_provider?: string | null;
            /** Parts */
            parts?: components["schemas"]["BirdVocalPartRead"][];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** BirdVocalPartRead */
        BirdVocalPartRead: {
            /**
             * Call Type
             * @default unknown
             */
            call_type: string;
            /** Channel */
            channel?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Ends At Seconds */
            ends_at_seconds: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Species Code */
            species_code: string;
            /** Species Common Name */
            species_common_name: string;
            /** Species Scientific Name */
            species_scientific_name?: string | null;
            /** Starts At Seconds */
            starts_at_seconds: number;
        };
        /** CollectionAdminRead */
        CollectionAdminRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Public */
            is_public: boolean;
            /** Location Ids */
            location_ids?: string[];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Session Ids */
            session_ids?: string[];
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CollectionCreate */
        CollectionCreate: {
            /** Description */
            description?: string | null;
            /**
             * Is Public
             * @default true
             */
            is_public: boolean;
            /** Location Ids */
            location_ids?: string[];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Session Ids */
            session_ids?: string[];
            /** Slug */
            slug: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Title */
            title: string;
        };
        /** CollectionDetailRead */
        CollectionDetailRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Location Count
             * @default 0
             */
            location_count: number;
            /** Locations */
            locations?: components["schemas"]["LocationRead"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Session Count
             * @default 0
             */
            session_count: number;
            /** Sessions */
            sessions?: components["schemas"]["SessionRead"][];
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CollectionSummaryRead */
        CollectionSummaryRead: {
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Location Count
             * @default 0
             */
            location_count: number;
            /**
             * Session Count
             * @default 0
             */
            session_count: number;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            /** Title */
            title: string;
        };
        /** CollectionUpdate */
        CollectionUpdate: {
            /** Description */
            description?: string | null;
            /** Is Public */
            is_public?: boolean | null;
            /** Location Ids */
            location_ids?: string[] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Session Ids */
            session_ids?: string[] | null;
            /** Slug */
            slug?: string | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Title */
            title?: string | null;
        };
        /**
         * CoordinateVisibility
         * @enum {string}
         */
        CoordinateVisibility: "exact_public" | "approximate_public" | "hidden_public";
        /** DawnCurrentResponse */
        DawnCurrentResponse: {
            /** Active Locations */
            active_locations: components["schemas"]["DawnLocation"][];
            /** Cache Key */
            cache_key: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Next Locations */
            next_locations: components["schemas"]["DawnLocation"][];
            window: components["schemas"]["DawnWindowConfig"];
        };
        /** DawnFollowResponse */
        DawnFollowResponse: {
            /** Cache Key */
            cache_key: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Locations */
            locations: components["schemas"]["DawnLocation"][];
            window: components["schemas"]["DawnWindowConfig"];
        };
        /** DawnLocation */
        DawnLocation: {
            /** Civil Dawn At */
            civil_dawn_at?: string | null;
            /** Local Date */
            local_date: string;
            /** Local Time */
            local_time: string;
            location: components["schemas"]["AtlasPoint"];
            /** Minutes Until Sunrise */
            minutes_until_sunrise?: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "active" | "upcoming" | "past" | "polar";
            /** Sunrise At */
            sunrise_at?: string | null;
            /** Window Ends At */
            window_ends_at?: string | null;
            /** Window Starts At */
            window_starts_at?: string | null;
        };
        /** DawnWindowConfig */
        DawnWindowConfig: {
            /** After Minutes */
            after_minutes: number;
            /** Before Minutes */
            before_minutes: number;
            /** Refresh Seconds */
            refresh_seconds: number;
        };
        /** DependencyStatus */
        DependencyStatus: {
            /** Detail */
            detail?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /** FeaturedSessionRead */
        FeaturedSessionRead: {
            /** Description */
            description: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Featured Sort Order */
            featured_sort_order?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            location: components["schemas"]["LocationRead"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            api: components["schemas"]["DependencyStatus"];
            postgres: components["schemas"]["DependencyStatus"];
            redis: components["schemas"]["DependencyStatus"];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /**
         * JobType
         * @enum {string}
         */
        JobType: "audio_pipeline";
        /** LocationCreate */
        LocationCreate: {
            /** @default exact_public */
            coordinate_visibility: components["schemas"]["CoordinateVisibility"];
            /** Country Code */
            country_code?: string | null;
            /** Description */
            description?: string | null;
            /** Exact Latitude */
            exact_latitude: number;
            /** Exact Longitude */
            exact_longitude: number;
            /** Habitat */
            habitat?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Public Latitude */
            public_latitude?: number | null;
            /** Public Longitude */
            public_longitude?: number | null;
            /** Region */
            region?: string | null;
            /** @default none */
            sensitivity_level: components["schemas"]["SensitivityLevel"];
            /** Slug */
            slug: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /** LocationRead */
        LocationRead: {
            coordinate_visibility: components["schemas"]["CoordinateVisibility"];
            /** Coordinates Protected */
            readonly coordinates_protected: boolean;
            /** Country Code */
            country_code: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Habitat */
            habitat: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Public Latitude */
            public_latitude?: number | null;
            /** Public Longitude */
            public_longitude?: number | null;
            /** Region */
            region: string | null;
            sensitivity_level: components["schemas"]["SensitivityLevel"];
            /** Slug */
            slug: string;
            /** Timezone */
            timezone: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LocationUpdate */
        LocationUpdate: {
            coordinate_visibility?: components["schemas"]["CoordinateVisibility"] | null;
            /** Country Code */
            country_code?: string | null;
            /** Description */
            description?: string | null;
            /** Exact Latitude */
            exact_latitude?: number | null;
            /** Exact Longitude */
            exact_longitude?: number | null;
            /** Habitat */
            habitat?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name?: string | null;
            /** Public Latitude */
            public_latitude?: number | null;
            /** Public Longitude */
            public_longitude?: number | null;
            /** Region */
            region?: string | null;
            sensitivity_level?: components["schemas"]["SensitivityLevel"] | null;
            /** Slug */
            slug?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /**
             * Status
             * @default logged_out
             */
            status: string;
        };
        /** MediaAssetCreate */
        MediaAssetCreate: {
            /** Checksum */
            checksum?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Enqueue Processing
             * @default true
             */
            enqueue_processing: boolean;
            /** @default source_audio */
            kind: components["schemas"]["MediaKind"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Mime Type
             * @default audio/wav
             */
            mime_type: string;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Storage Key */
            storage_key: string;
        };
        /** MediaAssetRead */
        MediaAssetRead: {
            /** Checksum */
            checksum: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Seconds */
            duration_seconds: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["MediaKind"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Mime Type */
            mime_type: string;
            /** @default uploaded */
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Size Bytes */
            size_bytes: number | null;
        };
        /**
         * MediaKind
         * @enum {string}
         */
        MediaKind: "audio" | "source_audio" | "master_audio" | "streaming_rendition" | "audio_stream";
        /** MembershipRead */
        MembershipRead: {
            /** Expires At */
            expires_at?: string | null;
            /** Id */
            id?: string | null;
            /** Is Entitled */
            is_entitled: boolean;
            /** Plan */
            plan: string;
            /** Starts At */
            starts_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "inactive" | "active" | "cancelled" | "expired";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MembershipUpdate */
        MembershipUpdate: {
            /** Expires At */
            expires_at?: string | null;
            /**
             * Plan
             * @default member
             */
            plan: string;
            /**
             * Status
             * @enum {string}
             */
            status: "inactive" | "active" | "cancelled" | "expired";
        };
        /** PlaybackGrantRead */
        PlaybackGrantRead: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Refresh After Seconds
             * @default 600
             */
            refresh_after_seconds: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Status
             * @default ready
             */
            status: string;
            /** Stream Url */
            stream_url: string;
        };
        /** ProcessingJobRead */
        ProcessingJobRead: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Attempt Count */
            attempt_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            job_type: components["schemas"]["JobType"];
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["JobStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProcessingStatus
         * @enum {string}
         */
        ProcessingStatus: "pending" | "uploaded" | "queued" | "processing" | "ready" | "failed";
        /** ProcessingStatusRead */
        ProcessingStatusRead: {
            latest_job?: components["schemas"]["ProcessingJobRead"] | null;
            /** Media Assets */
            media_assets: components["schemas"]["AdminMediaAssetRead"][];
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** RecordingIntegrityRead */
        RecordingIntegrityRead: {
            /**
             * Human Noise Level
             * @default unknown
             */
            human_noise_level: string;
            /** Microphone Setup */
            microphone_setup?: string | null;
            /**
             * Post Processing
             * @default Not yet reviewed
             */
            post_processing: string;
            /** Recordist Notes */
            recordist_notes?: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** SearchResult */
        SearchResult: {
            atlas_point?: components["schemas"]["AtlasPoint"] | null;
            /** Habitat */
            habitat?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Session Slug */
            session_slug?: string | null;
            /** Slug */
            slug: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "location" | "session";
        };
        /**
         * SensitivityLevel
         * @enum {string}
         */
        SensitivityLevel: "none" | "low" | "medium" | "high" | "protected";
        /**
         * SessionAccess
         * @enum {string}
         */
        SessionAccess: "public" | "members_only" | "draft" | "private";
        /** SessionAnnotationRead */
        SessionAnnotationRead: {
            /**
             * Annotation Type
             * @default editorial_note
             */
            annotation_type: string;
            /** Confidence */
            confidence?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Label */
            label: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Offset Seconds */
            offset_seconds: number;
        };
        /** SessionCreate */
        SessionCreate: {
            /** @default public */
            access_level: components["schemas"]["SessionAccess"];
            /** Description */
            description?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Featured Sort Order */
            featured_sort_order?: number | null;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** @default pending */
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Recorder */
            recorder?: string | null;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Weather */
            weather?: string | null;
        };
        /** SessionDetailRead */
        SessionDetailRead: {
            /** @default public */
            access_level: components["schemas"]["SessionAccess"];
            /** Annotations */
            annotations?: components["schemas"]["SessionAnnotationRead"][];
            bird_parts?: components["schemas"]["BirdPartsResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Featured Sort Order */
            featured_sort_order?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            location: components["schemas"]["LocationRead"];
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Media Assets */
            media_assets?: components["schemas"]["MediaAssetRead"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** @default pending */
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Recorder */
            recorder?: string | null;
            recording_integrity?: components["schemas"]["RecordingIntegrityRead"];
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            waveform?: components["schemas"]["WaveformRead"];
            /** Weather */
            weather?: string | null;
        };
        /** SessionRead */
        SessionRead: {
            /** @default public */
            access_level: components["schemas"]["SessionAccess"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Featured Sort Order */
            featured_sort_order?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Media Assets */
            media_assets?: components["schemas"]["MediaAssetRead"][];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** @default pending */
            processing_status: components["schemas"]["ProcessingStatus"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Recorder */
            recorder?: string | null;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Weather */
            weather?: string | null;
        };
        /** SessionUpdate */
        SessionUpdate: {
            access_level?: components["schemas"]["SessionAccess"] | null;
            /** Description */
            description?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Featured Sort Order */
            featured_sort_order?: number | null;
            /** Is Featured */
            is_featured?: boolean | null;
            /** Location Id */
            location_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            processing_status?: components["schemas"]["ProcessingStatus"] | null;
            /** Recorded At */
            recorded_at?: string | null;
            /** Recorder */
            recorder?: string | null;
            /** Slug */
            slug?: string | null;
            /** Title */
            title?: string | null;
            /** Weather */
            weather?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserRead"];
        };
        /** UserRead */
        UserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Role
             * @enum {string}
             */
            role: "member" | "editor" | "admin";
        };
        /** UserRoleUpdate */
        UserRoleUpdate: {
            /**
             * Role
             * @enum {string}
             */
            role: "member" | "editor" | "admin";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WaveformRead */
        WaveformRead: {
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Peaks */
            peaks?: number[];
            /**
             * Sample Rate
             * @default 1
             */
            sample_rate: number;
            /** Session Id */
            session_id?: string | null;
            /**
             * Status
             * @default placeholder
             */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_events_api_v1_admin_audit_events_get: {
        parameters: {
            query?: {
                event_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_collection_api_v1_admin_collections_post: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_collection_api_v1_admin_collections__collection_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path: {
                collection_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_location_api_v1_admin_locations_post: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_location_api_v1_admin_locations__location_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_location_api_v1_admin_locations__location_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_admin_api_v1_admin_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_asset_processing_api_v1_admin_media_assets__asset_id__process_post: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingStatusRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_membership_api_v1_admin_memberships__user_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_admin_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_admin_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_api_v1_admin_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_asset_api_v1_admin_sessions__session_id__assets_post: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaAssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMediaAssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_session_processing_api_v1_admin_sessions__session_id__processing_get: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingStatusRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_role_api_v1_admin_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-orna-admin"?: string | null;
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_dawn_api_v1_atlas_dawn_current_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DawnCurrentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_follow_dawn_api_v1_atlas_dawn_follow_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DawnFollowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_atlas_points_api_v1_atlas_points_get: {
        parameters: {
            query?: {
                bbox?: string | null;
                zoom?: number;
                habitat?: string[] | null;
                time_mode?: "local" | "utc" | "dawn";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtlasPointsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                orna_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                orna_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collections_api_v1_collections_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummaryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_api_v1_collections__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locations_api_v1_locations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_location_api_v1_locations__locator__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locator: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_my_membership_api_v1_memberships_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_featured_sessions_api_v1_sessions_featured_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedSessionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__locator__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                locator: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_annotations_api_v1_sessions__session_id__annotations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionAnnotationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bird_parts_api_v1_sessions__session_id__bird_parts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BirdPartsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_playback_grant_api_v1_sessions__session_id__playback_grants_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackGrantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_waveform_api_v1_sessions__session_id__waveform_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaveformRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                orna_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
