import { expect, test } from "@playwright/test";

test("home page offers immediate free listening before atlas exploration", async ({ page }) => {
  let grantRequests = 0;
  page.on("request", (request) => {
    if (request.method() === "POST" && request.url().includes("/playback-grants")) grantRequests += 1;
  });

  await page.goto("/");
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Real places for focus, rest, and deep listening");
  await expect(page.getByRole("link", { name: "Skip to main content" })).toHaveAttribute(
    "href",
    "#main-content",
  );
  await page.keyboard.press("Tab");
  await expect(page.getByRole("link", { name: "Skip to main content" })).toBeFocused();

  await page.getByRole("button", { name: "Listen free" }).click();
  await expect.poll(() => grantRequests).toBe(1);
  await expect(page.locator(".hero").getByRole("link", { name: "Explore the atlas" })).toHaveAttribute("href", "/atlas");
});

test("home sample analytics is emitted only after playback starts", async ({ page }) => {
  const events: Array<{ name: string }> = [];
  await page.route("**/playback-grants", async (route) => {
    await route.fulfill({ status: 503, headers: { "Content-Type": "application/json" }, body: "{}" });
  });
  await page.exposeFunction("captureSampleAnalytics", (detail: { name: string }) => events.push(detail));
  await page.addInitScript(() => {
    window.addEventListener("orna:analytics", (event) => {
      void (window as typeof window & {
        captureSampleAnalytics: (detail: unknown) => Promise<void>;
      }).captureSampleAnalytics((event as CustomEvent).detail);
    });
  });

  await page.goto("/");
  await page.getByRole("button", { name: "Listen free" }).click();
  await expect(page.locator(".hero-sample").getByRole("alert")).toBeVisible();
  expect(events.filter((event) => event.name === "sample_play_started")).toEqual([]);
});

test("missing curated intent collections fall back to the atlas", async ({ page }) => {
  await page.route("**/api/v1/collections**", async (route) => {
    await route.fulfill({ status: 200, headers: { "Content-Type": "application/json" }, body: "[]" });
  });

  await page.goto("/");
  const paths = page.getByRole("region", { name: "Choose your listening path" });
  await expect(paths.getByRole("link", { name: /Focus/ })).toHaveAttribute("href", "/atlas");
  await expect(paths.getByRole("link", { name: /Restore/ })).toHaveAttribute("href", "/atlas");
  await expect(paths.getByRole("link", { name: /Unwind/ })).toHaveAttribute("href", "/atlas");
});

test("home page explains listening paths, proof, membership value, and common questions", async ({ page }) => {
  await page.goto("/");

  const listeningPaths = page.getByRole("region", { name: "Choose your listening path" });
  await expect(listeningPaths.getByRole("link", { name: /Focus/ })).toHaveAttribute(
    "href",
    "/atlas",
  );
  await expect(listeningPaths.getByRole("link", { name: /Explore/ })).toHaveAttribute(
    "href",
    "/atlas",
  );

  await expect(page.getByRole("region", { name: "Atlas in numbers" })).toContainText(
    "continuous field recordings",
  );
  await expect(page.getByRole("region", { name: "Listener stories" })).toBeVisible();

  const membership = page.getByRole("region", { name: "Membership comparison" });
  await expect(membership.getByRole("columnheader", { name: "Free" })).toBeVisible();
  await expect(membership.getByRole("columnheader", { name: "Member" })).toBeVisible();
  await expect(membership.getByText("Complete long-form sessions")).toBeVisible();

  const pricing = page.getByRole("region", { name: "One membership. The complete atlas." });
  await expect(pricing.getByRole("heading", { name: "One membership. The complete atlas." })).toBeVisible();
  await expect(pricing.getByText("Pricing is announced before payment")).toBeVisible();
  await expect(pricing.getByRole("link", { name: "Join early access" })).toHaveAttribute(
    "href",
    "/membership?mode=register",
  );

  const faq = page.getByRole("region", { name: "Frequently asked questions" });
  await expect(faq.getByText("Are these sounds generated by AI?")).toBeVisible();
  await expect(faq.getByText("Why are some coordinates hidden?")).toBeVisible();
});

test("home conversion links emit bounded analytics events", async ({ page }) => {
  const events: Array<{ name: string; placement: string; destination: string }> = [];
  const persistedEvents: unknown[] = [];
  await page.route("**/api/v1/analytics/events", async (route) => {
    persistedEvents.push(route.request().postDataJSON());
    await route.fulfill({
      status: 202,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ accepted: true }),
    });
  });
  await page.exposeFunction(
    "captureOrnaAnalytics",
    (detail: { name: string; placement: string; destination: string }) => {
      events.push(detail);
    },
  );
  await page.addInitScript(() => {
    window.addEventListener("orna:analytics", (event) => {
      const detail = (event as CustomEvent).detail;
      void (window as typeof window & {
        captureOrnaAnalytics: (value: unknown) => Promise<void>;
      }).captureOrnaAnalytics(detail);
    });
  });

  await page.goto("/");
  await page.getByRole("region", { name: "Choose your listening path" })
    .getByRole("link", { name: /Focus/ })
    .click();

  await expect.poll(() => events).toContainEqual({
    name: "listening_path_selected",
    placement: "intent_focus",
    destination: "/atlas",
  });
  await expect.poll(() => persistedEvents).toContainEqual({
    name: "listening_path_selected",
    placement: "intent_focus",
  });
});

test("analytics delivery failure never blocks conversion navigation", async ({ page }) => {
  await page.route("**/api/v1/analytics/events", async (route) => route.abort("failed"));
  await page.goto("/");

  await page.locator(".hero").getByRole("link", { name: "Explore the atlas" }).click();

  await expect(page).toHaveURL(/\/atlas$/);
  await expect(page.locator("main#main-content")).toBeVisible();
});

test("atlas route renders without a browser error", async ({ page }) => {
  await page.goto("/atlas?view=list");
  await expect(page.locator("main#main-content")).toBeVisible();
  await expect(page.getByLabel("Atlas list view")).toBeVisible();
  await expect(page.locator(".dawn-copy")).toHaveCSS("pointer-events", "none");
  await expect(page.locator(".dawn-copy .listen-pill")).toHaveCSS("pointer-events", "auto");
  await expect(page.getByRole("link", { name: "About" })).toHaveText("About");
  await expect(page.getByRole("button", { name: "Tune filters" })).toHaveCount(0);
});

test("current-location control selects the nearest public listening site", async ({ context, page }) => {
  await context.grantPermissions(["geolocation"], { origin: "http://127.0.0.1:3100" });
  await context.setGeolocation({ latitude: 59.43, longitude: 24.72 });
  await page.goto("/atlas?view=list");

  const locateButton = page.getByRole("button", { name: "Use current location" });
  await expect(locateButton).toBeEnabled();
  await locateButton.click();

  await expect(page.getByRole("status")).toHaveText("Nearest listening location: Pine Marsh.");
  await expect(page.locator(".dawn-copy strong")).toHaveText("Pine Marsh");
});

test("atlas loads the interactive Cesium globe on a mobile viewport", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const cesiumResponse = page.waitForResponse((response) =>
    response.url().endsWith("/cesium/Cesium.js"),
  );

  await page.goto("/atlas");

  await expect.poll(async () => (await cesiumResponse).status()).toBe(200);
  const canvas = page.locator(".cesium-widget canvas");
  await expect(canvas).toHaveCount(1);
  await expect(canvas).toBeVisible();
  await expect(page.locator(".cesium-credit-logoContainer")).toBeHidden();

  const box = await canvas.boundingBox();
  expect(box?.width).toBeGreaterThan(200);
  expect(box?.height).toBeGreaterThan(200);
});

test("enter recenters the resized globe on the selected location at a closer zoom", async ({ page }) => {
  await page.goto("/atlas");

  const globe = page.getByLabel("Interactive Cesium globe");
  await expect(page.locator(".cesium-widget canvas")).toBeVisible();
  await expect(globe).toHaveAttribute("data-focus-height", "1500000");

  await page.evaluate(() => {
    const cesiumWindow = window as typeof window & {
      Cesium?: { Camera: { prototype: { flyTo: (options: unknown) => unknown } } };
      atlasFocusProbe?: Array<{ sidePanelVisible: boolean; canvasMatchesHost: boolean }>;
    };
    const cameraPrototype = cesiumWindow.Cesium!.Camera.prototype;
    const originalFlyTo = cameraPrototype.flyTo;
    cesiumWindow.atlasFocusProbe = [];
    cameraPrototype.flyTo = function patchedFlyTo(options: unknown) {
      const host = document.querySelector<HTMLElement>(".cesium-host");
      const canvas = host?.querySelector<HTMLCanvasElement>("canvas");
      const pixelRatio = window.devicePixelRatio || 1;
      cesiumWindow.atlasFocusProbe!.push({
        sidePanelVisible: document.querySelector(".atlas-side-panel") !== null,
        canvasMatchesHost: Boolean(
          host
          && canvas
          && Math.abs(canvas.width - host.clientWidth * pixelRatio) <= 1
          && Math.abs(canvas.height - host.clientHeight * pixelRatio) <= 1
        ),
      });
      return originalFlyTo.call(this, options);
    };
  });

  await page.getByRole("button", { name: "Enter", exact: true }).click();

  await expect.poll(() => page.evaluate(() => {
    const probe = (window as typeof window & {
      atlasFocusProbe?: Array<{ sidePanelVisible: boolean; canvasMatchesHost: boolean }>;
    }).atlasFocusProbe;
    return probe?.at(-1) ?? null;
  })).toEqual({ sidePanelVisible: true, canvasMatchesHost: true });
});

test("membership route exposes login and registration controls", async ({ page }) => {
  await page.goto("/membership");
  await expect(page.getByRole("heading", { level: 1, name: "Membership" })).toBeVisible();
  await expect(page.locator("form").getByRole("button", { name: "Sign in" })).toBeVisible();
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page.getByLabel("Email")).toBeVisible();
  await expect(page.getByLabel("Password")).toHaveAttribute("minlength", "12");
});

test("membership registration link opens the registration form", async ({ page }) => {
  await page.goto("/membership?mode=register");

  await expect(page.getByRole("button", { name: "Create account", pressed: true })).toBeVisible();
  await expect(page.locator("form").getByRole("button", { name: "Create account" })).toBeVisible();
  await expect(page.getByLabel("Password")).toHaveAttribute("minlength", "12");
});

test("membership registration emits a completion event without personal data", async ({ page }) => {
  await page.route("**/api/v1/auth/register", async (route) => {
    await route.fulfill({
      status: 201,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        id: "50000000-0000-4000-8000-000000000002",
        email: "new-listener@example.com",
        role: "member",
        is_active: true,
        created_at: "2026-07-17T00:00:00Z",
      }),
    });
  });
  await page.addInitScript(() => {
    (window as typeof window & { __analytics?: unknown[] }).__analytics = [];
    window.addEventListener("orna:analytics", (event) => {
      (window as typeof window & { __analytics?: unknown[] }).__analytics?.push((event as CustomEvent).detail);
    });
  });
  await page.goto("/membership?mode=register");
  await page.getByLabel("Email").fill("new-listener@example.com");
  await page.getByLabel("Password").fill("correct horse battery staple");
  await page.locator("form").getByRole("button", { name: "Create account" }).click();

  await expect.poll(() => page.evaluate(() => (
    window as typeof window & { __analytics?: unknown[] }
  ).__analytics ?? [])).toEqual([{
    name: "registration_completed",
    placement: "membership_form",
  }]);
  await expect(page.getByRole("status")).toContainText("You’re on the early access list");
});

test("an authenticated member sees the active entitlement state", async ({ page }) => {
  await page.route("**/api/v1/memberships/me", async (route) => {
    await route.fulfill({
      status: 200,
      headers: {
        "Access-Control-Allow-Credentials": "true",
        "Access-Control-Allow-Origin": "http://127.0.0.1:3100",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        id: "60000000-0000-4000-8000-000000000001",
        user_id: "50000000-0000-4000-8000-000000000001",
        status: "active",
        plan: "member",
        starts_at: "2026-07-01T00:00:00Z",
        expires_at: null,
        is_entitled: true,
      }),
    });
  });

  await page.goto("/membership");
  await page.getByLabel("Email").fill("member@example.com");
  await page.getByLabel("Password").fill("correct horse battery staple");
  await page.locator("form").getByRole("button", { name: "Sign in" }).click();

  await expect(page.getByRole("heading", { name: "member@example.com" })).toBeVisible();
  await expect(page.getByText("Member sessions unlocked")).toBeVisible();
  await expect(page.getByText("active", { exact: true })).toBeVisible();
});
